### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by CinquinAndy** [For-Hives/ForVoyez-Doc#2]
- [ ] [project doc] Mise en place de la CI / CD
- [ ] [project doc] Mise en place de renovate
- [ ] [project doc] Mise en place de prettier
- [ ] [project doc] Mise en place de ESLint
- [ ] [project doc] Mise en place de Husky
- [ ] [project doc] Mise en place des bonnes règles CSS
- [ ] [project doc] Clean des éléments qui ne sont pas nécessaires
- [ ] [project doc] Ecriture de la bonne documentation
- [ ] [project doc] Changement des couleurs
